server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
            uri: lb://user
            predicates:
              - Path=/user/**
            filters:
              - RewritePath=/user/(?<path>.*), /$\{path}
        - id: renting
            uri: lb://renting
            predicates:
              - Path=/renting/**
            filters:
              - RewritePath=/renting/(?<path>.*), /$\{path}
        - id: advertisement
            uri: lb://advertisement
            predicates:
              - Path=/advertisement/**
            filters:
              - RewritePath=/advertisement/(?<path>.*), /$\{path}
        - id: messaging
            uri: lb://messaging
            predicates:
              - Path=/messaging/**
            filters:
              - RewritePath=/messaging/(?<path>.*), /$\{path}
        - id: comment
            uri: lb://comment
            predicates:
              - Path=/comment/**
            filters:
              - RewritePath=/comment/(?<path>.*), /$\{path}
        - id: cart
            uri: lb://cart
            predicates:
              - Path=/cart/**
            filters:
              - RewritePath=/cart/(?<path>.*), /$\{path}